---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: synch_dev_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: DEV_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: dev
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: synch_staging_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: STAGING_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: staging
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: synch_production_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: production
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: build
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t cerberus-ui-service:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push

#- name: run_test_dev
#  pull: always
#  image: quay.io/ukhomeofficedigital/cop-cypress:6.3.0-node13
#  commands:
#    - export CYPRESS_CACHE_FOLDER=/home/node/.cache/Cypress
#    - npm ci
#    - npm run cypress:test:dev
#  when:
#    branch:
#      exclude:
#        - master
#    event:
#      - push

- name: vulnerability-scan
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: cerberus-ui-service:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: true
    TOLERATE: low
    WHITELIST_FILE: whitelist
  when:
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cerberus-ui-service
    tags: ${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  when:
    branch:
    - main
    event:
    - push
volumes:
  - name: dockersock
    temp: {}

---
kind: pipeline
type: kubernetes
name: test-and-deploy

depends_on:
  - build

platform:
  os: linux
  arch: amd64

steps:
- name: run_tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-cypress:6.3.0-node13
  commands:
    - npm ci
    - npm run cypress:test:dev
  when:
    event:
      - push

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export CERBERUS_UI_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    DEPLOY_ENV: dev
    KEYCLOAK_AUTH_URL:
      from_secret: DEV_KEYCLOAK_URL
    KEYCLOAK_CLIENT_ID:
      from_secret: DEV_CERBERUS_UI_SERVICE_KEYCLOAK_CLIENT_ID
    KEYCLOAK_REALM:
      from_secret: DEV_KEYCLOAK_REALM
    CERBERUS_UI_IMAGE: quay.io/ukhomeofficedigital/cerberus-ui-service
    CERBERUS_UI_NAME: cerberus-ui-service
    CERBERUS_UI_PORT: 8080
    CERBERUS_UI_URL:
      from_secret: DEV_CERBERUS_UI_SERVICE_URL
    KUBE_NAMESPACE:
      from_secret: DEV_KUBE_NAMESPACE_COP_CERBERUS
    KUBE_SERVER:
      from_secret: DEV_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: DEV_CERBERUS_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
  when:
    branch:
    - main
    event:
    - push

- name: deploy_to_staging
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export CERBERUS_UI_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    DEPLOY_ENV: staging
    KEYCLOAK_AUTH_URL:
      from_secret: STAGING_KEYCLOAK_URL
    KEYCLOAK_CLIENT_ID:
      from_secret: STAGING_CERBERUS_UI_SERVICE_KEYCLOAK_CLIENT_ID
    KEYCLOAK_REALM:
      from_secret: STAGING_KEYCLOAK_REALM
    CERBERUS_UI_IMAGE: quay.io/ukhomeofficedigital/cerberus-ui-service
    CERBERUS_UI_NAME: cerberus-ui-service
    CERBERUS_UI_PORT: 8080
    CERBERUS_UI_URL:
      from_secret: STAGING_CERBERUS_UI_SERVICE_URL
    KUBE_NAMESPACE:
      from_secret: STAGING_KUBE_NAMESPACE_COP_CERBERUS
    KUBE_SERVER:
      from_secret: STAGING_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: STAGING_CERBERUS_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
  when:
    branch:
    - main
    event:
    - promote
    target:
    - staging


- name: deploy_to_production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export CERBERUS_UI_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    DEPLOY_ENV: production
    KEYCLOAK_AUTH_URL:
      from_secret: PRODUCTION_KEYCLOAK_URL
    KEYCLOAK_CLIENT_ID:
      from_secret: PRODUCTION_CERBERUS_UI_SERVICE_KEYCLOAK_CLIENT_ID
    KEYCLOAK_REALM:
      from_secret: PRODUCTION_KEYCLOAK_REALM
    CERBERUS_UI_IMAGE: quay.io/ukhomeofficedigital/cerberus-ui-service
    CERBERUS_UI_NAME: cerberus-ui-service
    CERBERUS_UI_PORT: 8080
    CERBERUS_UI_URL:
      from_secret: PRODUCTION_CERBERUS_UI_SERVICE_URL
    KUBE_NAMESPACE:
      from_secret: PRODUCTION_KUBE_NAMESPACE_COP_CERBERUS
    KUBE_SERVER:
      from_secret: PRODUCTION_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: PRODUCTION_CERBERUS_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
  when:
    branch:
    - main
    event:
    - promote
    target:
    - production

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - main
    event:
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  volumes:
    - name: dockersock
      path: /var/run

- name: cerberus-ui
  image: quay.io/ukhomeofficedigital/cerberus-ui-service:$${DRONE_COMMIT_SHA}
  volumes:
     - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

- name: anchore-submission-server
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server

...
