apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube/cert.yml
  - kube/deployment.yml
  - kube/ingress.yml
  - kube/service.yml
  - kube/network-policy.yml

secretGenerator:
  - name: secret
    env: kube/secret.env
    type: Opaque

configMapGenerator:
  - name: config
    env: kube/config.env

images:
  - name: quay.io/ukhomeofficedigital/cerberus-ui-service
    newTag: $(CERBERUS_UI_TAG)

vars:
  - name: CERBERUS_UI_URL
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.CERBERUS_UI_URL
  - name: KUBE_NAMESPACE
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.KUBE_NAMESPACE
  - name: CERBERUS_UI_TAG
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
    fieldref:
      fieldpath: data.CERBERUS_UI_TAG

configurations:
  - kube/kustomizeconfig.yaml
