apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cerberus-ui-service-pod-cmio
spec:
  secretName: cerberus-ui-service-pod-cmio
  issuerRef:
    name: platform-ca
    kind: ClusterIssuer
  commonName: cerberus-ui-service.$(KUBE_NAMESPACE).svc.cluster.local
  dnsNames:
    - localhost
    - 127.0.0.1
